# Generated by Django 2.1.4 on 2018-12-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='will be the first non-empty line of the pad content if left empty', max_length=255, null=True)),
                ('url', models.URLField()),
                ('date', models.DateField()),
                ('format', models.CharField(choices=[('markdown', 'Markdown'), ('mediawiki', 'MediaWiki'), ('etherpad', 'EtherPad')], default='etherpad', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='will be deduced from the pad title if left empty', null=True)),
                ('content', models.TextField(blank=True, editable=False, null=True)),
                ('html', models.TextField(blank=True, editable=False, null=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
