# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text=b'will be the first non-empty line of the pad content if left empty', max_length=255, null=True)),
                ('url', models.URLField()),
                ('date', models.DateField()),
                ('format', models.CharField(choices=[(b'mediawiki', b'MediaWiki'), (b'markdown', b'Markdown'), (b'etherpad', b'EtherPad')], max_length=255)),
                ('slug', models.SlugField(blank=True, help_text=b'will be deduced from the pad title if left empty', null=True)),
                ('content', models.TextField(blank=True, editable=False, null=True)),
                ('html', models.TextField(blank=True, editable=False, null=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Orga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='orga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Orga'),
        ),
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together=set([('url', 'orga')]),
        ),
    ]
